import pygame
import random
import math

# -------------------- CONFIGURATION --------------------
SCREEN_SIZE = 600
MAP_SIZE = 100  # grid size
CELL_SIZE = SCREEN_SIZE // MAP_SIZE
SEA_LEVEL = 0.5  # normalized height
AGENT_LIFETIME = 1500  # number of steps an agent can take
NUM_COASTLINE_AGENTS = 5  # initial number of coastline agents

# Colors
WATER_COLOR = (0, 0, 128)
LAND_COLOR = (34, 139, 34)
COAST_COLOR = (210, 180, 140)

# -------------------- ENVIRONMENT --------------------
class Terrain:
    def __init__(self, size):
        self.size = size
        # initialize map under sea level
        level = SEA_LEVEL - 0.1
        self.height_map = []
        for y in range(size):                            # rows
            row = []
            for x in range(size):                        # columns
                row.append(level)
            self.height_map.append(row)
    def elevate_point(self, x, y, amount=0.1):
        if 0 <= x < self.size and 0 <= y < self.size:
            self.height_map[y][x] += amount
            if self.height_map[y][x] > 1.0:
                self.height_map[y][x] = 1.0

    def get_height(self, x, y):
        if 0 <= x < self.size and 0 <= y < self.size:
            return self.height_map[y][x]
        return SEA_LEVEL - 0.1

    def draw(self, screen):
        for y in range(self.size):
            for x in range(self.size):
                h = self.height_map[y][x]
                if h < SEA_LEVEL:
                    color = WATER_COLOR
                elif SEA_LEVEL <= h < SEA_LEVEL + 0.05:
                    color = COAST_COLOR
                else:
                    color = LAND_COLOR
                pygame.draw.rect(screen, color, (x*CELL_SIZE, y*CELL_SIZE, CELL_SIZE, CELL_SIZE))


# -------------------- AGENT --------------------
#sense a local 3×3 patch, 
# choose a valid exit cell based on a simple potential‐field heuristic,
# elevate it, move there, 
# and repeat until the agent runs out of life.
#------------------------------------------------
class CoastlineAgent:
    def __init__(self, terrain, x, y, direction=(1,0), lifespanTokens=AGENT_LIFETIME):
        self.terrain = terrain
        self.x = x #current grid x
        self.y = y #current grid y
        self.dir = direction # direction (dx, dy)
        self.lifespanTokens = lifespanTokens # number of steps agent can take before becoming inactive

    def step(self):# returns False if agent is inactive    
        if self.lifespanTokens <= 0:
            return False  # agent inactive

        # generate attractor and repulsor
        #two random points are generated by taking the agent’s current position
        #and adding a uniform offset in [-5,5] in both coordinates.
        #the idea is that the agent will try to move toward the attractor 
        # and away from the repulsor
        attractor = (self.x + random.randint(-5,5), self.y + random.randint(-5,5))
        repulsor = (self.x + random.randint(-5,5), self.y + random.randint(-5,5))

        #look around 
        # find candidate points in a 3x3 neighborhood      
        #examines the 3×3 neighborhood centred on its current location.
        #any neighbour whose height is still below SEA_LEVEL + 0.05 (i.e. water or very shallow coast)
        #is added to a candidates list.
        candidates = []
        for dx in [-1,0,1]:
            for dy in [-1,0,1]:
                nx, ny = self.x + dx, self.y + dy
                if 0 <= nx < self.terrain.size and 0 <= ny < self.terrain.size:
                    if self.terrain.get_height(nx, ny) < SEA_LEVEL + 0.05:
                        candidates.append((nx, ny))
        #no candidates?
        #if the list is empty the agent simply walks one step in its current dir,
        # decrements lifespanTokens, and returns. 
        # it will keep going straight 
        # until it finds some low‑height cell, 
        # or until its tokens run out.
        if not candidates:
            # move in direction until suitable point found
            self.x += self.dir[0]
            self.y += self.dir[1]
            self.lifespanTokens -= 1
            return True

        # score candidates based on attractor/repulsor
        #a neighbour that is closer to the attractor 
        # and farther from the repulsor gets a higher score.
        def score(point):
            ax, ay = attractor
            rx, ry = repulsor
            px, py = point
            attract_dist = math.hypot(px - ax, py - ay)
            repulse_dist = math.hypot(px - rx, py - ry)
            return repulse_dist - attract_dist  # closer to attractor, higher score

        #move and raise terrain
        #the candidate with the maximum score is chosen, 
        # the agent’s x,y are updated to that cell
        #terrain.elevate_point() is called to bump the height there
        #finally the token count is decremented
        best_point = max(candidates, key=score)
        bx, by = best_point
        self.terrain.elevate_point(bx, by)
        self.x, self.y = bx, by
        self.lifespanTokens -= 1
        return True


# -------------------- MAIN PROGRAM --------------------
def main():
    pygame.init()
    screen = pygame.display.set_mode((SCREEN_SIZE, SCREEN_SIZE))
    pygame.display.set_caption("Terrain Generation: Coastline Phase")
    clock = pygame.time.Clock()

    def make_agents(t):
        agents = []
        for _ in range(NUM_COASTLINE_AGENTS):
            edge = random.choice(['top','bottom','left','right'])
            if edge == 'top':
                x, y = random.randint(0, MAP_SIZE-1), 0
                dir = (0,1)
            elif edge == 'bottom':
                x, y = random.randint(0, MAP_SIZE-1), MAP_SIZE-1
                dir = (0,-1)
            elif edge == 'left':
                x, y = 0, random.randint(0, MAP_SIZE-1)
                dir = (1,0)
            else:  # right
                x, y = MAP_SIZE-1, random.randint(0, MAP_SIZE-1)
                dir = (-1,0)
            agents.append(CoastlineAgent(t, x, y, dir))
        return agents

    terrain = Terrain(MAP_SIZE)
    agents = make_agents(terrain)

    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False
                elif event.key == pygame.K_SPACE:
                    # restart: create a fresh terrain and new agents
                    terrain = Terrain(MAP_SIZE)
                    agents = make_agents(terrain)

        # update agents
        for agent in agents:
            agent.step()

        # draw terrain
        terrain.draw(screen)
        pygame.display.flip()
        clock.tick(60)

    pygame.quit()

if __name__ == "__main__":
    main()